local M = {}
M.keymaps = {
    { mode = "n",   bind = '["x]<Del>',                                               explanation = "Delete character under the cursor [into register x] (not |linewise|)." },
    { mode = "v",   bind = '["x]<Del>',                                               explanation = "Delete the highlighted text [into register x]." },

    { mode = "n",   bind = '["x]X',                                                   explanation = "Delete [count] characters before the cursor [into register x]." },
    { mode = "n",   bind = '["x]x',                                                   explanation = "Delete [count] characters under and after the cursor [into register x]." },

    { mode = "n",   bind = '["x]d{motion}',                                           explanation = "Delete text that {motion} moves over [into register x]." },
    { mode = "v",   bind = '["x]d',                                                   explanation = "Delete the highlighted text [into register x]." },
    { mode = "n",   bind = '["x]dl',                                                  explanation = "Delete [count] characters under and after the cursor [into register x]." },
    { mode = "n",   bind = '["x]dh',                                                  explanation = "Delete [count] characters before the cursor [into register x]." },
    { mode = "n",   bind = '["x]dd',                                                  explanation = "Delete [count] lines [into register x] |linewise|." },
    { mode = "n",   bind = '["x]D',                                                   explanation = "Delete characters under the cursor until the end of the line and [count]-1 more lines [into register x](not |linewise|)." },
    { mode = "v",   bind = '["x]D',                                                   explanation = "Delete the highlighted lines [into register x]." },
    { mode = "vb",  bind = '["x]D',                                                   explanation = "Delete the highlighted text plus all text until the end of the line [into register x]." },
    { mode = "cmd", bind = ':d[elete] [x]',                                           explanation = "Delete [range] lines (default: current line) [into register x]." },
    { mode = "cmd", bind = ':d[elete] [x] {count}',                                   explanation = "Delete {count} lines, starting with [range] (default: current line) [into register x]." },

    { mode = "n",   bind = '["x]y{motion}',                                           explanation = "Yank [count] lines [into register x] |linewise|." },
    { mode = "n",   bind = '["x]yy',                                                  explanation = "Yank [count] lines [into register x] |linewise|." },
    { mode = "n",   bind = '["x]Y',                                                   explanation = "Yank [count] lines [into register x] |linwwise|." },
    { mode = "n",   bind = '["x]zy{motion}',                                          explanation = "Yank {motion} text [into register x]." },
    { mode = "v",   bind = '["x]y',                                                   explanation = "Yank the highlighted text into [into register x]." },
    { mode = "v",   bind = '["x]Y',                                                   explanation = "Yank the highlighted lines [into register x]." },
    { mode = "v",   bind = '["x]zy',                                                  explanation = "Yank the highlighted text without whitespaces [into register x]." },
    { mode = "cmd", bind = '[range]y[ank] [x]',                                       explanation = "Yank [range] lines [into register x]." },
    { mode = "cmd", bind = '[range]y[ank] [x] {count}',                               explanation = "Yank {count} lines, starting with last line number in [range][into register x]." },

    { mode = "v",   bind = '["x]x',                                                   explanation = "Delete the highlighted text [into register x]." },
    { mode = "v",   bind = '["x]x',                                                   explanation = "Delete the highlighted text [into register x]." },
    { mode = "v",   bind = '["x]X',                                                   explanation = "Delete the highlighted text [into register x] or use *v_X* *v_D*." },

    { mode = "v",   bind = '["x]CTRL-H',                                              explanation = "Delete the highlighted text [into register x]." },
    { mode = "v",   bind = '["x]<BS>',                                                explanation = "When in Select mode: Delete the highlighted text [into register x]." },
    --
    { mode = "n",   bind = '["x]J',                                                   explanation = "Join [count] lines." },
    { mode = "v",   bind = '["x]J',                                                   explanation = "Join highlighted lines." },
    { mode = "n",   bind = '["x]gJ',                                                  explanation = "Join [count] lines. Dont insert or remove any spaces." },
    { mode = "v",   bind = '["x]gJ',                                                  explanation = "Join highlighted lines. Dont insert or remove any spaces." },
    { mode = "cmd", bind = '[range]j[oin][!] [flags]',                                explanation = "Join [range] lines. Dont insert or remove any spaces." },
    { mode = "cmd", bind = '[range]j[oin][!] {count} [flags]',                        explanation = "Join {count} lines starting with [range]. Dont insert or remove any spaces." },

    { mode = "n",   bind = 'R',                                                       explanation = "Enter Replace mode." },
    { mode = "n",   bind = 'r{char}',                                                 explanation = "Replace [count] characters starting under the cursor with {char}" },
    { mode = "n",   bind = 'gR',                                                      explanation = "Enter Virtual Replace mode." },
    { mode = "n",   bind = 'gr{char}',                                                explanation = "Replace the virtual character under the cursor with {char}." },
    { mode = "v",   bind = '["x]r{char}',                                             explanation = "Replace all selected characters by {char}." },
    { mode = "v",   bind = '["x]R',                                                   explanation = "Delete highlighted lines [into register x] and start insert." },

    { mode = "n",   bind = '["x]c{motion}',                                           explanation = "Delete {motion} text [into register x] and start insert." },
    { mode = "n",   bind = '["x]c',                                                   explanation = "Delete from the cursor position to the end of the line and [count]-1 more lines [into register x] and start insert |linewise|." },
    { mode = "v",   bind = '["x]c',                                                   explanation = "Delete highlighted text [into register x] and start insert." },
    { mode = "n",   bind = '["x]cc',                                                  explanation = "Delete [count] lines [into register x] and start insert |linewise|" },
    { mode = "v",   bind = '["x]C',                                                   explanation = "Delete the highlighted lines [into register x] and start insert." },

    { mode = "n",   bind = '["x]s',                                                   explanation = "Delete [count] characters [into register x] and start insert (not |linewise|)." },
    { mode = "v",   bind = '["x]s',                                                   explanation = "Delete highlighted text [into register x] and start insert." },
    { mode = "n",   bind = '["x]S',                                                   explanation = "Delete [count] lines [into register x] and start insert |linewise|." },
    { mode = "v",   bind = '["x]S',                                                   explanation = "Delete highlighted lines [into register x] and start insert." },

    { mode = "n",   bind = '~',                                                       explanation = "Switch case of [count] characters starting under the cursor and move cursor to the right." },
    { mode = "n",   bind = '~{motion}',                                               explanation = "Switch case of {motion} text." },
    { mode = "n",   bind = 'g~{motion}',                                              explanation = "Switch case of {motion} text." },
    { mode = "n",   bind = 'g~~',                                                     explanation = "Switch case of current line." },
    { mode = "n",   bind = 'g~g~',                                                    explanation = "Switch case of current line." },
    { mode = "v",   bind = '~',                                                       explanation = "Switch cas of highlighted text." },

    { mode = "v",   bind = 'U',                                                       explanation = "Make highlighted text uppercase." },
    { mode = "n",   bind = 'gU{motion}',                                              explanation = "Make {motion} text uppercase." },
    { mode = "n",   bind = 'gUgU',                                                    explanation = "Make current line uppercase." },
    { mode = "n",   bind = 'gUU',                                                     explanation = "Make current line uppercase." },

    { mode = "v",   bind = 'u',                                                       explanation = "Make highlighted text lowercase." },
    { mode = "n",   bind = 'gu{motion}',                                              explanation = "Make {motion} text lowercase." },
    { mode = "n",   bind = 'gugU',                                                    explanation = "Make current line lowercase." },
    { mode = "n",   bind = 'guu',                                                     explanation = "Make current line lowercase." },

    { mode = "n",   bind = 'g?{motion}',                                              explanation = "Rot13 encode {motion} text." },
    { mode = "v",   bind = 'g?',                                                      explanation = "Rot13 encode highlighted text." },
    { mode = "n",   bind = 'g?g?',                                                    explanation = "Rot13 encode current line." },
    { mode = "n",   bind = 'g??',                                                     explanation = "Rot13 encode current line." },
    -- possible bind: :s/\v<(.)(\w*)/\u\1\L\2/g for all title case

    { mode = "n",   bind = 'CTRL-A',                                                  explanation = "Add [count] to the number or alphabetic character at or after the cursor." },
    { mode = "v",   bind = 'CTRL-A',                                                  explanation = "Add [count] to the highlighted number or alphabetic text." },
    { mode = "v",   bind = 'g CTRL-A',                                                explanation = "Incrementingly add [count] to the highlighted number or alphabetic character." },

    { mode = "n",   bind = 'CTRL-X',                                                  explanation = "Subtract [count] from the number or alphabetic character at or after the cursor." },
    { mode = "v",   bind = 'CTRL-X',                                                  explanation = "Subtract [count] from the highlighted number or alphabetic text." },
    { mode = "v",   bind = 'g CTRL-X',                                                explanation = "Incrementingly subtract [count] from the highlighted number or alphabetic character." },

    { mode = "n",   bind = '<{motion}',                                               explanation = "Shift {motion} [count] lines one $shiftwidth leftwards." },
    { mode = "n",   bind = '<<',                                                      explanation = "Shift [count] lines one $shiftwidth leftwards." },
    { mode = "v",   bind = '<',                                                       explanation = "Shift the highlighted lines [count] $shiftwidth leftwards." },

    { mode = "n",   bind = '>{motion}',                                               explanation = "Shift {motion} [count] lines one $shiftwidth rightwards." },
    { mode = "n",   bind = '>>',                                                      explanation = "Shift [count] lines one $shiftwidth rightwards." },
    { mode = "v",   bind = '>',                                                       explanation = "Shift the highlighted lines [count] $shiftwidth rightwards." },

    { mode = "n",   bind = '<{motion}',                                               explanation = "Shift {motion} [count] lines one $shiftwidth leftwards." },
    { mode = "n",   bind = '<<',                                                      explanation = "Shift [count] lines one $shiftwidth leftwards." },
    { mode = "v",   bind = '<',                                                       explanation = "Shift the highlighted lines [count] $shiftwidth leftwards." },

    { mode = "cmd", bind = ':[range]<',                                               explanation = "Shift [range] lines one $shiftwidth left. Repeat '<' for shifting multiple $shiftwidths." },
    { mode = "cmd", bind = ':[range]< {count}',                                       explanation = "Shift {count} lines one $shiftwidth left, starting with [range] (default current line |cmdline-ranges|). Repeat '<' for shifting multiple $shiftwidths." },
    { mode = "cmd", bind = ':[range]le[ft] [indent]',                                 explanation = "Left align lines in [range]. Sets the indent in the lines to [indent] (default 0)." },
    { mode = "cmd", bind = ':[range]> [flags]',                                       explanation = "Shift [range] lines one $shiftwidth right. Repeat '>' for shifting multiple $shiftwidths. See |ex-flags| for [flags]." },
    { mode = "cmd", bind = ':[range]> {count} [flags]',                               explanation = "Shift {count} lines one $shiftwidth right, starting with [range] (default current line |cmdline-ranges|). Repeat '>' for shifting multiple $shiftwidths. See |ex-flags| for [flags]." },

    { mode = "cmd", bind = ':[range]!{filter} [!][arg]',                              explanation = "Filter {range} lines through the external program {filter}." },
    { mode = "n",   bind = '!{motion}{filter}',                                       explanation = "Filter {motion} text lines through the external program {filter}." },
    { mode = "n",   bind = '!!{filter}',                                              explanation = "Filter [count] lines, starting from the current line, through the external program {filter}." },
    { mode = "v",   bind = '!{filter}',                                               explanation = "Filter the highlighted lines through the external program {filter}." },
    { mode = "n",   bind = '==',                                                      explanation = "Filter [count] lines like with = filter." },
    { mode = "v",   bind = '={motion}',                                               explanation = "Filter the highlighted lines like using the = filter. Formats {motion} lines." },

    { mode = "cmd", bind = ':[range]s[ubstitute]/{pattern}/{string}/[flags] [count]', explanation = "For each line in [range], replace a match of {pattern} with {string}." },
    { mode = "cmd", bind = ':[range]s[ubstitute] [flags] [count]',                    explanation = "Repeat last :s[ubstitute] with same search pattern and substitute string, but without the same flags. You may add [flags]." },
    { mode = "cmd", bind = ':[range]~[&][flags] [count]',                             explanation = "Repeat last :s[ubstitute] with optional " },
    { mode = "cmd", bind = '&',                                                       explanation = "Synonym for `:s[ubstitute]`. Note that the flags are not remembered." },
    { mode = "cmd", bind = '&-default',                                               explanation = "Mapped to ':&&<CR>' by default." },
    { mode = "cmd", bind = 'g&',                                                      explanation = "Same as `:%s//~/&`" },
    { mode = "cmd", bind = ':[range]sno[magic] ...',                                  explanation = "Same as `:s[ubstitute]`, but always use 'nomagic'." },
    { mode = "cmd", bind = ':[range]sm[agic] ...',                                    explanation = "Same as `:s[ubstitute]`, but always use 'magic'." },
    { mode = "cmd", bind = '&&',                                                      explanation = "Repeat the last :s[ubstitute] with same pattern, substitute, and flags." },

    { mode = "cmd", bind = ':[range]ret[ab][!] [new_tabstop]',                        explanation = "Replace all sequences of white-space containing <Tab> with new strings." },

    { mode = "cmd", bind = ':reg[isters]',                                            explanation = "Display the type and content of all numbered and named registers." },
    { mode = "cmd", bind = ':reg[isters] {arg}',                                      explanation = "Display the type and content of a numbered or named register." },
    { mode = "cmd", bind = ':reg[isters] {arg}',                                      explanation = "Display the type and content of a numbered or named register." },
    { mode = "cmd", bind = 'di[splay] [arg]',                                         explanation = "Display the type and content of [arg] register or all registers if no [arg] is specified." },

    { mode = "n",   bind = '["x]p',                                                   explanation = "Put text [from register x] after cursor [count] times." },
    { mode = "n",   bind = '["x]P',                                                   explanation = "Put text [from register x] before cursor [count] times." },
    { mode = "n",   bind = '["x]<MiddleMouse>',                                       explanation = "Put text [from register x] before cursor [count] times." },
    { mode = "n",   bind = '["x]gp',                                                  explanation = "Put text [from register x] but leave the cursor just after the new text." },
    { mode = "cmd", bind = ':[line]pu[t] [x]',                                        explanation = "Put text [from register x] after line [line]." },
    { mode = "cmd", bind = ':[line]pu[t]! [x]',                                       explanation = "Put text [from register x] after line [line]." },
    { mode = "n",   bind = '["x]]p',                                                  explanation = "Put the text [from register x] after the cursor [count] times and adjust the indent to the current line." },
    { mode = "n",   bind = '["x][p',                                                  explanation = "Put the text [from register x] before the cursor [count] times and adjust the indent to the current line." },
    { mode = "n",   bind = '["x]]P',                                                  explanation = "Put the text [from register x] before the cursor [count] times and adjust the indent to the current line." },
    { mode = "n",   bind = '["x][P',                                                  explanation = "Put the text [from register x] before the cursor [count] times and adjust the indent to the current line." },
    { mode = "n",   bind = '["x]zp',                                                  explanation = "Put the text [from register x] after cursor [count] times but without trailing whitespaces." },
    { mode = "n",   bind = '["x]zP',                                                  explanation = "Put the text [from register x] before cursor [count] times but without trailing whitespaces." },
    { mode = "cmd", bind = ':[range]co[py] {address}',                                explanation = "Copy the lines given by [range] to belpw the line given by {address}." },
    { mode = "cmd", bind = ':t',                                                      explanation = "Copy the lines given by [range] to belpw the line given by {address}." },
    { mode = "cmd", bind = ':[range]m[ove] {address}',                                explanation = "Move the lines given by [range] to below the line given by {address}." },

    { mode = "cmd", bind = ':[range]ce[nter] [width]',                                explanation = "Center lines in [range] between [width] columns." },
    { mode = "cmd", bind = ':[range]ri[ght] [width]',                                 explanation = "Right-align lines in [range] at [width] columns." },
    { mode = "cmd", bind = ':[range]le[ft] [indent]',                                 explanation = "Left-align lines in [range]. Sets the indent in the lines to [indent]." },

    { mode = "n",   bind = 'gq{motion}',                                              explanation = "Format the lines that {motion} moves over." },
    { mode = "v",   bind = 'gq',                                                      explanation = "Format the highlighted text." },
    { mode = "n",   bind = 'gqgq',                                                    explanation = "Format [count] lines, starting from current line." },
    { mode = "n",   bind = 'gqq',                                                     explanation = "Format [count] lines, starting from current line." },

    { mode = "n",   bind = 'gw{motion}',                                              explanation = "Formats the lines that {motion} moves over. Puts the cursor back in the same position of the text." },
    { mode = "v",   bind = 'gw',                                                      explanation = "Formats  the highlighted text and puts the cursor back in the same position of the text" },
    { mode = "n",   bind = 'gwgw',                                                    explanation = "Formats the current line and puts the cursor back in the same position of the text." },
    { mode = "n",   bind = 'gww',                                                     explanation = "Formats the current line and puts the cursor back in the same position of the text." },
}
return M
