local M = {}
M.keymaps = {
    { mode = "n",   mod = "",       bind = "v",                     explanation = "Visual Mode" },
    { mode = "n",   mod = "Ctrl",   bind = "v",                     explanation = "Visual Block Mode" },
    { mode = "n",   mod = "",       bind = "V",                     explanation = "Visual Line Mode" },
    { mode = "n",   mod = "",       bind = "vf[char]",              explanation = "Select to next [char]" },
    { mode = "n",   mod = "",       bind = "vF[char]",              explanation = "Select to previous [char]" },
    { mode = "n",   mod = "",       bind = "v(i/a)[delim]",         explanation = "Select within/(and with) [delim]" },
    { mode = "n",   mod = "",       bind = "v(i/a)w",               explanation = "Select entire/(and up to next) word" },
    { mode = "n",   mod = "",       bind = "v(i/a)W",               explanation = "Select entire/(and up to next) continuous string" },
    { mode = "n",   mod = "",       bind = "v(i/a)b",               explanation = "Select within/(and with) next nearest [delim]" },
    { mode = "n",   mod = "",       bind = "v(i/a)B",               explanation = "Select within/(and with) current [delim]" },
    { mode = "n",   mod = "",       bind = "v(i/a)p",               explanation = "Select current/(and up to next) paragraph" },

    { mode = "n",   mod = "",       bind = "C",                     explanation = "Replace to end of line" },
    { mode = "n",   mod = "",       bind = "cc",                    explanation = "Replace entire line" },
    { mode = "n",   mod = "",       bind = "cw",                    explanation = "Replace to end of word" },
    { mode = "n",   mod = "",       bind = "cf[char]",              explanation = "Replace to next [char]" },
    { mode = "n",   mod = "",       bind = "cF[char]",              explanation = "Replace to previous [char]" },
    { mode = "n",   mod = "",       bind = "c(i/a)[delim]",         explanation = "Replace within/(and with) [delim]" },
    { mode = "n",   mod = "",       bind = "c(i/a)w",               explanation = "Replace entire/(and up to next) word" },
    { mode = "n",   mod = "",       bind = "c(i/a)W",               explanation = "Replace entire/(and up to next) continuous string" },
    { mode = "n",   mod = "",       bind = "c(i/a)b",               explanation = "Replace within/(and with) next nearest [delim]" },
    { mode = "n",   mod = "",       bind = "c(i/a)B",               explanation = "Replace within/(and with) current [delim]" },
    { mode = "n",   mod = "",       bind = "c(i/a)p",               explanation = "Replace current/(and up to next) paragraph" },

    { mode = "n",   mod = "",       bind = "D",                     explanation = "Delete to end of line" },
    { mode = "n",   mod = "",       bind = "dd",                    explanation = "Delete entire line" },
    { mode = "n",   mod = "",       bind = "df[char]",              explanation = "Delete to next [char]" },
    { mode = "n",   mod = "",       bind = "dF[char]",              explanation = "Delete to previous [char]" },
    { mode = "n",   mod = "",       bind = "d(i/a)[delim]",         explanation = "Delete within/(and with) [delim]" },
    { mode = "n",   mod = "",       bind = "d(i/a)w",               explanation = "Delete entire/(and up to next) word" },
    { mode = "n",   mod = "",       bind = "d(i/a)W",               explanation = "Delete entire/(and up to next) continuous string" },
    { mode = "n",   mod = "",       bind = "d(i/a)b",               explanation = "Delete within/(and with) next nearest [delim]" },
    { mode = "n",   mod = "",       bind = "d(i/a)B",               explanation = "Delete within/(and with) current [delim]" },
    { mode = "n",   mod = "",       bind = "d(i/a)p",               explanation = "Delete current/(and up to next) paragraph" },

    { mode = "n",   mod = "",       bind = "Y",                     explanation = "Yank to end of line" },
    { mode = "n",   mod = "",       bind = "y",                     explanation = "Yank entire line" },
    { mode = "n",   mod = "<leader>", bind = "y",                     explanation = "Yank into system clipboard" },
    { mode = "n",   mod = "",       bind = "yf[char]",              explanation = "Yank to next [char]" },
    { mode = "n",   mod = "",       bind = "yF[char]",              explanation = "Yank to previous [char]" },
    { mode = "n",   mod = "",       bind = "y(i/a)[delim]",         explanation = "Yank within/(and with) [delim]" },
    { mode = "n",   mod = "",       bind = "y(i/a)w",               explanation = "Yank entire/(and up to next) word" },
    { mode = "n",   mod = "",       bind = "y(i/a)W",               explanation = "Yank entire/(and up to next) continuous string" },
    { mode = "n",   mod = "",       bind = "y(i/a)b",               explanation = "Yank within/(and with) next nearest [delim]" },
    { mode = "n",   mod = "",       bind = "y(i/a)B",               explanation = "Yank within/(and with) current [delim]" },
    { mode = "n",   mod = "",       bind = "y(i/a)p",               explanation = "Yank current/(and up to next) paragraph" },

    { mode = "n",   mod = "",       bind = "u",                     explanation = "Undo" },
    { mode = "n",   mod = "Ctrl",   bind = "r",                     explanation = "Redo" },
    { mode = "n",   mod = "",       bind = "q[buffer]",             explanation = "Record macro into [buffer]" },
    { mode = "n",   mod = "",       bind = "@[buffer]",             explanation = "Replay macro from [buffer]" },
    { mode = "n",   mod = "",       bind = "==",                    explanation = "Format line" },
    { mode = "n",   mod = "",       bind = "gg=G",                  explanation = "Format entire document" },
    { mode = "n",   mod = "",       bind = "~",                     explanation = "Change selected characters to upper/lower case" },
    { mode = "v*",  mod = "",       bind = "U",                     explanation = "Change selected characters to upper/lower case" },
    { mode = "n",   mod = "",       bind = "<<",                    explanation = "Remove one indent" },
    { mode = "n",   mod = "",       bind = ">>",                    explanation = "Add one indent" },

    { mode = "n",   mod = "",       bind = "f[char]",               explanation = "Find next occurrence of [char]" },
    { mode = "n",   mod = "",       bind = "F[char]",               explanation = "Find previous occurrence of [char]" },
    { mode = "n",   mod = "",       bind = ";",                     explanation = "Next search result of f/F search" },
    { mode = "n",   mod = "",       bind = ",",                     explanation = "Previous search result of f/F search" },
    { mode = "n",   mod = "",       bind = "n",                     explanation = "Next search result of / search" },
    { mode = "n",   mod = "",       bind = "N",                     explanation = "Previous search result of / search" },

    { mode = "n",   mod = "",       bind = "P",                     explanation = "Paste into new line above" },
    { mode = "n",   mod = "",       bind = "p",                     explanation = "Paste into new line below" },
    { mode = "n",   mod = "<leader>", bind = "p",                     explanation = "Paste without loosing buffer" },
    { mode = "n",   mod = "",       bind = "O",                     explanation = "Insert into new line above" },
    { mode = "n",   mod = "",       bind = "o",                     explanation = "Insert into new line below" },
    { mode = "n",   mod = "",       bind = "s",                     explanation = "Replace char and enter Insert Mode" },
    { mode = "n",   mod = "<leader>", bind = "s",                     explanation = "Replace all occurrences of word" },
    { mode = "n",   mod = "",       bind = "I",                     explanation = "Insert at start of line" },
    { mode = "n",   mod = "",       bind = "A",                     explanation = "Append to end of line" },
    { mode = "v*",  mod = "",       bind = "K",                     explanation = "Move entire line(s) up" },
    { mode = "v*",  mod = "",       bind = "J",                     explanation = "Move entire line(s) down" },

    { mode = "n",   mod = "",       bind = "zR",                    explanation = "Open all folds" },
    { mode = "n",   mod = "",       bind = "zM",                    explanation = "Close all folds" },
    { mode = "n",   mod = "",       bind = "zo",                    explanation = "Open current fold" },
    { mode = "n",   mod = "",       bind = "zc",                    explanation = "Close current fold" },
    { mode = "vl",  mod = "",       bind = "zf",                    explanation = "Create new fold from lines" },

    { mode = "n",   mod = "",       bind = "k",                     explanation = "[Movement] Up" },
    { mode = "n",   mod = "",       bind = "j",                     explanation = "[Movement] Down" },
    { mode = "n",   mod = "",       bind = "h",                     explanation = "[Movement] Left" },
    { mode = "n",   mod = "",       bind = "l",                     explanation = "[Movement] Right" },
    { mode = "n",   mod = "",       bind = "gg",                    explanation = "[Movement] Go to top of file" },
    { mode = "n",   mod = "",       bind = "G",                     explanation = "[Movement] Go to bottom of file" },
    { mode = "n",   mod = "",       bind = "H",                     explanation = "[Movement] Go cursor to top of screen" },
    { mode = "n",   mod = "",       bind = "M",                     explanation = "[Movement] Go cursor to middle of screen" },
    { mode = "n",   mod = "",       bind = "L",                     explanation = "[Movement] Go cursor to bottom of screen" },
    { mode = "n",   mod = "",       bind = "zz",                    explanation = "Shift editor to center" },
    { mode = "n",   mod = "",       bind = "{",                     explanation = "[Movement] Go to start of block" },
    { mode = "n",   mod = "",       bind = "}",                     explanation = "[Movement] Go to end of block" },

    { mode = "n",   mod = "",       bind = "w",                     explanation = "[Movement] Go to next word" },
    { mode = "n",   mod = "",       bind = "W",                     explanation = "[Movement] Go to next word after continuous string" },
    { mode = "n",   mod = "",       bind = "b",                     explanation = "[Movement] Go to previous word" },
    { mode = "n",   mod = "",       bind = "B",                     explanation = "[Movement] Go to word before continuous string" },
    { mode = "n",   mod = "",       bind = "e",                     explanation = "[Movement] Go to end of next word" },
    { mode = "n",   mod = "",       bind = "E",                     explanation = "[Movement] Go to end of continuous string" },
    { mode = "n",   mod = "",       bind = "%",                     explanation = "[Movement] Go to closing/opening syntax" },

    -- Custom Commands
    { mode = "n",   mod = "",       bind = "gd",                    explanation = "[LSP] Go to definition" },
    { mode = "n",   mod = "",       bind = "gD",                    explanation = "[LSP] Go to declaration" },
    { mode = "n",   mod = "",       bind = "gr",                    explanation = "[LSP] Go to reference" },
    { mode = "n",   mod = "",       bind = "gi",                    explanation = "[LSP] Go to implementation" },
    { mode = "n",   mod = "<leader>", bind = "D",                     explanation = "[LSP] Go to type definition" },
    { mode = "n",   mod = "",       bind = "K",                     explanation = "[LSP] Info" },
    { mode = "n",   mod = "<leader>", bind = "wa",                    explanation = "[LSP] Add workspace folder" },
    { mode = "n",   mod = "<leader>", bind = "wr",                    explanation = "[LSP] Remove workspace folder" },
    { mode = "n",   mod = "<leader>", bind = "wl",                    explanation = "[LSP] List workspace folders" },
    { mode = "n",   mod = "<leader>", bind = "rn",                    explanation = "[LSP] Rename" },
    { mode = "n",   mod = "<leader>", bind = "ca",                    explanation = "[LSP] Code action" },
    { mode = "n",   mod = "<leader>", bind = "f",                     explanation = "[LSP] Format buffer" },

    { mode = "n",   mod = "<leader>", bind = "pv",                    explanation = "Netrw" },
    { mode = "n",   mod = "<leader>", bind = "ü",                     explanation = "Compile current file" },
    { mode = "n",   mod = "<leader>", bind = "ö",                     explanation = "Run this file" },
    { mode = "n",   mod = "",       bind = "J",                     explanation = "Join line below to this one" },
    { mode = "n",   mod = "",       bind = "K",                     explanation = "Split line to new line here" },

    { mode = "n",   mod = "<leader>", bind = "gc",                    explanation = "Git add . and commit -m" },
    { mode = "n",   mod = "<leader>", bind = "gp",                    explanation = "Git push" },
    { mode = "n",   mod = "<leader>", bind = "get",                   explanation = "Git stash local changes and pull" },

    { mode = "cmd", mod = "",       bind = ":w",                    explanation = "[Command] Write file" },
    { mode = "cmd", mod = "",       bind = ":wq",                   explanation = "[Command] Write file and quit" },
    { mode = "cmd", mod = "",       bind = ":q",                    explanation = "[Command] Quit buffer" },
    { mode = "cmd", mod = "",       bind = ":qa",                   explanation = "[Command] Quit all buffers" },
    { mode = "cmd", mod = "",       bind = ":qa!",                  explanation = "[Command] Force quit all buffers" },

    { mode = "cmd", mod = "",       bind = ":sp",                   explanation = "[Command] Horizontal split" },

    { mode = "cmd", mod = "",       bind = ":!",                    explanation = "[Command] Execute shell command" },

    { mode = "cmd", mod = "",       bind = ":/[String]",            explanation = "[Command] Search for string in file" },
    { mode = "cmd", mod = "",       bind = ":%s/[String]/[String]", explanation = "[Command] Replace string with other string" },
}

return M
